-- Unifind — seed data: university_resources.
--
-- Ported from Nevora's src/data/universityInternationalResources.js —
-- see 0012's header and TRANSFER_NOTES.md for what was and wasn't kept.
--
-- Coverage: Nevora only researched this level of detail (7 categories:
-- international office, housing, visa support, buddy programme, student
-- services, Erasmus, arrival info) for 7 of the 35 universities — its
-- own "Задача 19" scope, not yet extended to the rest. Honest partial
-- coverage, same discipline as everywhere else in this transfer: only
-- port real, sourced rows, leave everything else for a future pass
-- rather than inventing placeholder rows for the other 28 universities.

with src as (
  select * from jsonb_to_recordset($seed$[
    {"university_name": "Charles University", "category": "international_office", "title": "Central International Relations Office & Faculty Desks", "description": "Central incoming student coordinator hub for full-degree, foundation, and exchange students across all 17 faculties.", "link_title": "International Students Portal", "link_url": "https://cuni.cz/UKEN-198.html", "link_type": "official", "contact_type": "email", "contact_value": "incoming@cuni.cz", "contact_label": "Incoming Students"},
    {"university_name": "Charles University", "category": "housing", "title": "Charles University Dormitories & Refectories (KaM)", "description": "Accommodation in university halls (Hvězda, Větrník, Kajetánka, 17. listopadu) with online reservation via the ISKAM system.", "link_title": "Dormitories & Accommodation Portal", "link_url": "https://kam.cuni.cz/KAMEN-1.html", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Charles University", "category": "visa_support", "title": "Visa & Nostrification Advisory Service", "description": "Official study confirmations, internal foreign education recognition (direct assessment without municipal nostrification), and visa timeline support.", "link_title": "Visa & Legal Guide", "link_url": "https://cuni.cz/UKEN-367.html", "link_type": "guide", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Charles University", "category": "buddy_program", "title": "ESN CU Prague (Erasmus Student Network)", "description": "Student buddy program pairing arriving international students with local Czech mentors, plus Orientation Week excursions.", "link_title": "ESN CU Prague Buddy Network", "link_url": "https://esncuprague.cz/", "link_type": "portal", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Charles University", "category": "student_services", "title": "Carolina Centre — Student Services & Counseling", "description": "Free psychological counseling, career guidance, disability support, Czech language courses, and official UK student ID / ISIC card issuance.", "link_title": "Carolina Centre Portal", "link_url": "https://cuni.cz/UKEN-370.html", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Charles University", "category": "erasmus", "title": "Erasmus+ European & Global Mobility Office", "description": "Over 2,000 inter-institutional partner agreements across 30+ European and global institutions for semester/year abroad mobilities.", "link_title": "Erasmus+ Exchanges", "link_url": "https://cuni.cz/UKEN-145.html", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Charles University", "category": "arrival_info", "title": "Welcome Days & Prague Arrival Guide", "description": "Official arrival checklist, Prague public transit (PID Lítačka) setup, registration with Foreign Police within 3 working days, and campus tours.", "link_title": "Official Arrival Guide", "link_url": "https://cuni.cz/UKEN-369.html", "link_type": "guide", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Czech Technical University in Prague", "category": "international_office", "title": "CTU Department of Foreign Relations", "description": "Cross-university coordination for international degree and exchange students, based at the Dejvice campus.", "link_title": "Foreign Relations Office", "link_url": "https://www.cvut.cz/en/department-of-foreign-relations", "link_type": "official", "contact_type": "email", "contact_value": "international@cvut.cz", "contact_label": "International Desk"},
    {"university_name": "Czech Technical University in Prague", "category": "housing", "title": "CTU Service Facilities Administration (SÚZ)", "description": "8 dormitory complexes including the famous Strahov, Dejvice, and Podolí halls with online booking via ISKAM.", "link_title": "CTU Dormitory Administration", "link_url": "https://www.suz.cvut.cz/en", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Czech Technical University in Prague", "category": "visa_support", "title": "CTU International Visa & Nostrification Assistance", "description": "Internal institutional verification of secondary/university diplomas and official visa pack issuance (study + accommodation confirmations).", "link_title": "Nostrification & Visa Service", "link_url": "https://www.cvut.cz/en/nostrification", "link_type": "guide", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Czech Technical University in Prague", "category": "buddy_program", "title": "International Student Club CTU (ISC / ESN CTU in Prague)", "description": "Active buddy system, airport pickups, Prague orientation walks, and legendary welcome week parties.", "link_title": "ISC CTU Buddy Club", "link_url": "https://isc.cvut.cz/", "link_type": "portal", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Czech Technical University in Prague", "category": "student_services", "title": "CTU Career & Counseling Centre (CIPS & ELSA)", "description": "Career advisory, industry internships with Czech tech giants, psychological support, and IT infrastructure access.", "link_title": "CIPS Counseling Centre", "link_url": "https://www.cips.cvut.cz/en/", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Czech Technical University in Prague", "category": "erasmus", "title": "CTU Erasmus+ & ATHENS Exchange Network", "description": "Extensive European mobility agreements and specialized ATHENS intensive one-week engineering courses across Europe.", "link_title": "CTU International Exchanges", "link_url": "https://international.cvut.cz/en/", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Czech Technical University in Prague", "category": "arrival_info", "title": "CTU Orientation Week & Arrival Guide", "description": "Dejvice campus navigation, Czech SIM cards distribution during orientation, Prague transit ISIC discount setup, and Foreign Police registration.", "link_title": "Orientation Week Guide", "link_url": "https://international.cvut.cz/for-exchange-students/orientation-week/", "link_type": "guide", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Masaryk University", "category": "international_office", "title": "Masaryk University Centre for International Cooperation (CZS)", "description": "Komenského náměstí international hub managing admissions, visa guidance, and welcome activities for full-degree and exchange students.", "link_title": "CZS International Office", "link_url": "https://czs.muni.cz/en/", "link_type": "official", "contact_type": "email", "contact_value": "czs@muni.cz", "contact_label": "CZS Inquiries"},
    {"university_name": "Masaryk University", "category": "housing", "title": "MU Accommodation and Catering Services (SKM)", "description": "Vinařská, Kounicova, and Komárov halls of residence with booking managed directly through the ISKAM accommodation portal.", "link_title": "SKM Housing Portal", "link_url": "https://www.skm.muni.cz/en", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Masaryk University", "category": "visa_support", "title": "CZS Visa & Legal Guidance Hub", "description": "Assistance with long-term visa/residence permit applications, internal foreign education verification, and MOI appointments in Brno.", "link_title": "Visa Information", "link_url": "https://czs.muni.cz/en/student-czs/practical-information/visa", "link_type": "guide", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Masaryk University", "category": "buddy_program", "title": "ESN MUNI Brno Buddy System", "description": "Pairs each incoming international student with a local Brno student for train station meet-ups, dormitory check-in, and social events.", "link_title": "ESN MUNI Brno", "link_url": "https://esn.muni.cz/", "link_type": "portal", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Masaryk University", "category": "student_services", "title": "MU Career Centre & Teiresiás Support Centre", "description": "Comprehensive career workshops, JobCheckIN portal, psychological counseling, and renowned accessibility support.", "link_title": "MU Career Centre", "link_url": "https://kariera.muni.cz/en", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Masaryk University", "category": "erasmus", "title": "MU Erasmus+ & ISEP International Exchanges", "description": "Over 1,400 bilateral Erasmus+ partnerships and worldwide mobility via the Utrecht Network and ISEP consortium.", "link_title": "Exchange Programmes", "link_url": "https://czs.muni.cz/en/student-czs/exchange-students", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Masaryk University", "category": "arrival_info", "title": "Brno Arrival & Orientation Week Guide", "description": "Detailed Brno arrival instructions from Vienna/Prague airports, Brno DPMB public transport card, and foreign police registration.", "link_title": "Practical Arrival Information", "link_url": "https://czs.muni.cz/en/student-czs/practical-information", "link_type": "guide", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Prague University of Economics and Business", "category": "international_office", "title": "VŠE International Office (OZS)", "description": "Central coordinating department for English-taught degree programmes, international accreditations (EQUIS, AACSB), and incoming students.", "link_title": "OZS International Office", "link_url": "https://ozs.vse.cz/english/", "link_type": "official", "contact_type": "email", "contact_value": "ozs@vse.cz", "contact_label": "OZS Office"},
    {"university_name": "Prague University of Economics and Business", "category": "housing", "title": "VŠE Jarov & Rooseveltova Dormitories (SÚZ)", "description": "Guaranteed accommodation for newly enrolled full-degree international students applying within the deadline in the Jarov campus area.", "link_title": "SÚZ VŠE Dormitories", "link_url": "https://suz.vse.cz/en/", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Prague University of Economics and Business", "category": "visa_support", "title": "VŠE Visa Advising & Diploma Verification", "description": "Step-by-step visa documents package, institutional recognition of secondary and higher education diplomas, and embassy correspondence.", "link_title": "Visa Process Guide", "link_url": "https://admissions.vse.cz/visa-process/", "link_type": "guide", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Prague University of Economics and Business", "category": "buddy_program", "title": "ESN VSE Prague Buddy Programme", "description": "Personal student buddy matching, Prague airport/station pickups, trips across the Czech Republic, and Orientation Week icebreakers.", "link_title": "ESN VSE Prague", "link_url": "https://esnvseprague.cz/", "link_type": "portal", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Prague University of Economics and Business", "category": "student_services", "title": "VŠE Career Centre & Academic Psychological Counseling", "description": "Annual ŠANCE Job Fair connecting students with international consultancies, banks, and tech firms in Prague; multi-function ISIC cards.", "link_title": "VŠE Career Centre", "link_url": "https://kc.vse.cz/en/", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Prague University of Economics and Business", "category": "erasmus", "title": "CEMS & PIM Global Business Network / Erasmus+", "description": "Czechia’s sole member of the prestigious CEMS Global Alliance in Management Education and PIM network with 250+ top business school partners.", "link_title": "Exchange Partnerships", "link_url": "https://ozs.vse.cz/english/exchange-students/", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Prague University of Economics and Business", "category": "arrival_info", "title": "VŠE Orientation Week & Prague Survival Guide", "description": "Comprehensive introductory sessions, course registration workshops, Czech crash-courses, and practical life-in-Prague tips.", "link_title": "Orientation Week Schedule", "link_url": "https://ozs.vse.cz/english/exchange-students/orientation-week/", "link_type": "guide", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Palacký University Olomouc", "category": "international_office", "title": "UP Welcome Office & International Relations", "description": "Central Welcome Office supporting international degree and exchange students with pre-arrival counseling and campus life in Olomouc.", "link_title": "International Students Portal", "link_url": "https://www.upol.cz/en/students/exchange-students/", "link_type": "official", "contact_type": "email", "contact_value": "admissions@upol.cz", "contact_label": "Admissions Office"},
    {"university_name": "Palacký University Olomouc", "category": "housing", "title": "UP Accommodation & Dining Facilities (SKM)", "description": "Envelopa and Neředín campus dormitories offering affordable rooms within walking distance of faculties and university libraries.", "link_title": "SKM Dormitories", "link_url": "https://skm.upol.cz/en/", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Palacký University Olomouc", "category": "visa_support", "title": "UP Visa Guidance & Foreign Education Assessment", "description": "Official acceptance certificates for embassies, internal nostrification assessment, and local OAMP Olomouc assistance.", "link_title": "Visa Information", "link_url": "https://www.upol.cz/en/students/guide/visa/", "link_type": "guide", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Palacký University Olomouc", "category": "buddy_program", "title": "ESN UP Olomouc", "description": "Welcoming buddy network organizing train station pick-up in Olomouc, Welcome Days, and cultural events in the historic city centre.", "link_title": "ESN UP Olomouc", "link_url": "https://esn.upol.cz/", "link_type": "portal", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Palacký University Olomouc", "category": "student_services", "title": "UP Student Career Centre & Counseling Hub", "description": "Academic tutoring, psychological advice in English, language courses at the UČJ Language Centre, and university sports clubs.", "link_title": "Student Guide & Services", "link_url": "https://www.upol.cz/en/students/guide/", "link_type": "guide", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Palacký University Olomouc", "category": "erasmus", "title": "Aurora European University Alliance & Erasmus+", "description": "Member of the prestigious Aurora European Universities Alliance, unlocking seamless mobilities and joint courses across Europe.", "link_title": "Aurora Alliance at UP", "link_url": "https://aurora.upol.cz/en/", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Palacký University Olomouc", "category": "arrival_info", "title": "Olomouc Arrival Guide & Welcome Week", "description": "How to travel from Prague/Vienna airports to Olomouc by train (RegioJet/ČD/LeoExpress), local tram pass setup, and city registration.", "link_title": "Arrival Guide to Olomouc", "link_url": "https://www.upol.cz/en/students/guide/arrival/", "link_type": "guide", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Brno University of Technology", "category": "international_office", "title": "BUT Department of International Relations", "description": "Central international office coordinating engineering, IT, and architecture programs and international applicant support.", "link_title": "International Relations Office", "link_url": "https://www.vut.cz/en/international", "link_type": "official", "contact_type": "email", "contact_value": "international@vut.cz", "contact_label": "International Relations"},
    {"university_name": "Brno University of Technology", "category": "housing", "title": "BUT Halls of Residence & Dining Services (KaM)", "description": "Pod Palackého vrchem and Purkyňova dormitories, one of the largest modern student accommodation clusters in Czechia with sports grounds.", "link_title": "KaM VUT Dormitories", "link_url": "https://www.kam.vutbr.cz/english/", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Brno University of Technology", "category": "visa_support", "title": "BUT Visa & Educational Recognition Guidance", "description": "Direct university recognition of foreign secondary school and bachelor documents, plus required visa accommodation verification vouchers.", "link_title": "Nostrification Guide", "link_url": "https://www.vut.cz/en/admissions/nostrification", "link_type": "guide", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Brno University of Technology", "category": "buddy_program", "title": "ESN VUT Brno Buddy Programme", "description": "Volunteer Czech engineering students helping incoming internationals with arrival at Brno train stations, dormitory check-in, and local life.", "link_title": "ESN VUT Brno", "link_url": "https://esnvutbrno.cz/", "link_type": "portal", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Brno University of Technology", "category": "student_services", "title": "BUT Lifelong Learning & Counseling Institute (ICV)", "description": "Career advisory, industry connection days with Brno tech cluster companies, psychological counseling, and Czech language courses for foreigners.", "link_title": "ICV Counseling Institute", "link_url": "https://icv.vut.cz/en/", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Brno University of Technology", "category": "erasmus", "title": "EULiST European University Alliance & Erasmus+", "description": "Member of the EULiST European University Alliance connecting top technical universities across 10 European countries.", "link_title": "EULiST Alliance", "link_url": "https://www.vut.cz/en/international/eulist", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Brno University of Technology", "category": "arrival_info", "title": "BUT Welcome Guide & Brno Integration Steps", "description": "Step-by-step checklist: Brno public transport card (DPMB), opening a Czech bank account, Foreign Police reporting, and campus card activation.", "link_title": "Practical Arrival Guide", "link_url": "https://www.vut.cz/en/international/practical-info", "link_type": "guide", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Czech University of Life Sciences Prague", "category": "international_office", "title": "ČZU Welcome Centre & International Relations Office", "description": "Dedicated Welcome Centre located on the modern green campus in Prague-Suchdol, assisting international students from 100+ countries.", "link_title": "International Relations Department", "link_url": "https://www.czu.cz/en/r-9189-international-relations", "link_type": "official", "contact_type": "email", "contact_value": "international@czu.cz", "contact_label": "International Relations"},
    {"university_name": "Czech University of Life Sciences Prague", "category": "housing", "title": "ČZU Campus Dormitories & Campus Living", "description": "On-campus dormitories (Kolej Jih, Kolej A, BCD) where all academic buildings, dorms, cafeterias, and sports facilities are in one single green area.", "link_title": "ČZU Dormitory Administration (KaM)", "link_url": "https://kam.czu.cz/en/", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Czech University of Life Sciences Prague", "category": "visa_support", "title": "ČZU Visa & Nostrification Support Office", "description": "Assistance with visa document legalization, internal validation of foreign secondary school certificates, and embassy verification forms.", "link_title": "Nostrification & Visa Assistance", "link_url": "https://www.czu.cz/en/r-9190-study-at-czu/r-15873-nostrification", "link_type": "guide", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Czech University of Life Sciences Prague", "category": "buddy_program", "title": "ESN CZU Prague (Erasmus Student Network)", "description": "Student organization offering buddy pairing, airport pickup service, Suchdol campus tours, and weekend integration trips in Czechia.", "link_title": "ESN CZU Prague", "link_url": "https://esnczuprague.cz/", "link_type": "portal", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Czech University of Life Sciences Prague", "category": "student_services", "title": "ČZU Career Centre & Counseling Services", "description": "Agritech and environmental career fairs, psychological advisory in English, Czech language classes, and modern sports center.", "link_title": "ČZU Career Centre", "link_url": "https://kariernicentrum.czu.cz/en/", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Czech University of Life Sciences Prague", "category": "erasmus", "title": "Euroleague for Life Sciences (ELLS) & Erasmus+", "description": "Member of Euroleague for Life Sciences (ELLS), offering exclusive student exchange and summer schools with top European agricultural universities.", "link_title": "ELLS Network & Exchanges", "link_url": "https://www.czu.cz/en/r-9189-international-relations/r-10499-international-networks/r-10502-euroleague-for-life-sciences-ells", "link_type": "official", "contact_type": null, "contact_value": null, "contact_label": null},
    {"university_name": "Czech University of Life Sciences Prague", "category": "arrival_info", "title": "ČZU Welcome Week & Campus Orientation", "description": "Transportation from Prague airport to Suchdol (bus 107/147 from Dejvická), campus check-in, Lítačka student transport pass, and police registration.", "link_title": "Practical Arrival Guide", "link_url": "https://www.czu.cz/en/r-9190-study-at-czu/r-13840-practical-information", "link_type": "guide", "contact_type": null, "contact_value": null, "contact_label": null}
  ]$seed$) as x(
    university_name text, category text, title text, description text,
    link_title text, link_url text, link_type text,
    contact_type text, contact_value text, contact_label text
  )
),
resolved as (
  select u.id as university_id, src.category, src.title, src.description,
         src.link_title, src.link_url, src.link_type,
         src.contact_type, src.contact_value, src.contact_label
  from src
  join universities u on u.name = src.university_name and u.country_code = 'CZ'
)
insert into university_resources (
  university_id, category, title, description,
  link_title, link_url, link_type, contact_type, contact_value, contact_label
)
select university_id, category, title, description,
       link_title, link_url, link_type, contact_type, contact_value, contact_label
from resolved
on conflict (university_id, category) do nothing;
