-- Bulk university expansion, part 1: Western/Southern/Central Europe +
-- North America (user request: ≥30 per country where such institutions
-- exist). Terse rows (no marketing copy) — every criterion section is
-- filled afterwards by the shared idempotent pipeline at the bottom and
-- by two templated English programmes so each university is matchable.
--
-- Small countries (AT/CH/DK/FI/IE/NO/PT/SE) genuinely host fewer HEIs;
-- their full realistic inventory is included instead of padding with
-- duplicates.

-- ============================================================
-- Universities — bulk insert
-- ============================================================
insert into universities (
  name, slug, country_code, city, founded_year, student_count,
  ownership_type, city_size, website_url, published)
select d.name, d.slug, d.cc, d.city, d.yr, d.students, d.own, d.csz,
       d.site, true
from (values
-- ---------- GERMANY (30 additional) ----------
('Heidelberg University','heidelberg','DE','Heidelberg',1386,29000,'public','small','https://www.uni-heidelberg.de/index_e.html'),
('Humboldt-Universität zu Berlin','hu-berlin','DE','Berlin',1810,36000,'public','capital_or_large','https://www.hu-berlin.de/en/'),
('Freie Universität Berlin','fu-berlin','DE','Berlin',1948,37000,'public','capital_or_large','https://www.fu-berlin.de/en/'),
('Technische Universität Berlin','tu-berlin','DE','Berlin',1879,34000,'public','capital_or_large','https://www.tu.berlin/en/'),
('University of Bonn','uni-bonn','DE','Bonn',1818,35000,'public','medium','https://www.uni-bonn.de/en'),
('University of Göttingen','goettingen','DE','Göttingen',1737,30000,'public','small','https://www.uni-goettingen.de/en/'),
('University of Tübingen','tuebingen','DE','Tübingen',1477,27000,'public','small','https://uni-tuebingen.de/en/'),
('Goethe University Frankfurt','frankfurt','DE','Frankfurt',1914,45000,'public','capital_or_large','https://www.goethe-university-frankfurt.de/en/'),
('Universität Hamburg','uni-hamburg','DE','Hamburg',1919,42000,'public','capital_or_large','https://www.uni-hamburg.de/en/'),
('University of Cologne','uni-koeln','DE','Cologne',1388,44000,'public','capital_or_large','https://www.uni-koeln.de/en/'),
('University of Stuttgart','uni-stuttgart','DE','Stuttgart',1829,22000,'public','capital_or_large','https://www.uni-stuttgart.de/en/'),
('TU Dresden','tu-dresden','DE','Dresden',1828,29000,'public','capital_or_large','https://tu-dresden.de/en'),
('Leipzig University','uni-leipzig','DE','Leipzig',1409,29000,'public','capital_or_large','https://www.uni-leipzig.de/en/'),
('Friedrich-Alexander-Universität Erlangen-Nürnberg','fau','DE','Erlangen',1742,39000,'public','small','https://www.fau.eu/'),
('University of Würzburg','uni-wuerzburg','DE','Würzburg',1582,28000,'public','small','https://www.uni-wuerzburg.de/en/'),
('University of Münster','uni-muenster','DE','Münster',1780,44000,'public','medium','https://www.uni-muenster.de/en/'),
('Johannes Gutenberg University Mainz','uni-mainz','DE','Mainz',1477,33000,'public','medium','https://www.uni-mainz.de/eng/'),
('Christian-Albrechts-Universität zu Kiel','uni-kiel','DE','Kiel',1665,25000,'small','small','https://www.uni-kiel.de/en/'),
('Leibniz University Hannover','luh-hannover','DE','Hanover',1831,30000,'public','capital_or_large','https://www.uni-hannover.de/en/'),
('Karlsruhe Institute of Technology','kit','DE','Karlsruhe',1825,25000,'public','medium','https://www.kit.edu/english/'),
('TU Darmstadt','tu-darmstadt','DE','Darmstadt',1877,25000,'public','medium','https://www.tu-darmstadt.de/en/'),
('TU Braunschweig','tu-bs','DE','Braunschweig',1745,18000,'public','medium','https://www.tu-braunschweig.de/en/'),
('University of Duisburg-Essen','ude','DE','Duisburg',1654,40000,'public','capital_or_large',NULL),
('Universität Augsburg','uni-augsburg','DE','Augsburg',1970,21000,'public','medium',NULL),
('Universität Regensburg','uni-regensburg','DE','Regensburg',1962,21000,'public','small','https://www.ur.de/en/'),
('Ulm University','uni-ulm','DE','Ulm',1967,10000,'public','medium','https://www.uni-ulm.de/en/'),
('University of Konstanz','uni-konstanz','DE','Konstanz',1966,11000,'public','small','https://www.uni-konstanz.de/en/'),
('Mannheim University','uni-mannheim','DE','Mannheim',1967,12000,'public','medium','https://www.uni-mannheim.de/en/'),
('Friedrich Schiller University Jena','uni-jena','DE','Jena',1558,18000,'public','small','https://www.uni-jena.de/en'),
('Otto von Guericke University Magdeburg','ovgu','DE','Magdeburg',1993,14000,'public','medium','https://www.ovgu.de/en'),
('University of Rostock','uni-rostock','DE','Rostock',1419,14000,'public','medium','https://www.uni-rostock.de/en/'),
('University of Potsdam','uni-potsdam','DE','Potsdam',1991,22000,'public','medium','https://www.uni-potsdam.de/en/'),
-- ---------- POLAND (28 additional) ----------
('Adam Mickiewicz University Poznań','amu-poznan','PL','Poznań',1919,40000,'public','capital_or_large','https://amu.edu.pl/en'),
('University of Wrocław','uni-wroclaw','PL','Wrocław',1945,26000,'public','capital_or_large','https://uwr.edu.pl/en/'),
('University of Łódź','uni-lodz','PL','Łódź',1945,25000,'public','capital_or_large','https://uni.lodz.pl/en'),
('Nicolaus Copernicus University Toruń','ncu-torun','PL','Toruń',1945,27000,'public','medium','https://www.umk.pl/en/'),
('Maria Curie-Skłodowska University Lublin','umcs-lublin','PL','Lublin',1944,25000,'public','capital_or_large','https://www.umcs.pl/en'),
('University of Silesia Katowice','us-katowice','PL','Katowice',1968,26000,'public','capital_or_large','https://us.edu.pl/en/'),
('AGH University of Kraków','agh-krakow','PL','Kraków',1919,36000,'public','capital_or_large','https://www.agh.edu.pl/en/'),
('Gdańsk University of Technology','pg-gdansk','PL','Gdańsk',1904,25000,'public','capital_or_large','https://pg.edu.pl/international'),
('Poznań University of Technology','put-poznan','PL','Poznań',1955,21000,'public','capital_or_large','https://www.put.poznan.pl/en'),
('Łódź University of Technology','p-lodz','PL','Łódź',1945,18000,'public','capital_or_large','https://www.p.lodz.pl/en'),
('Wrocław University of Science and Technology','pwr-wroclaw','PL','Wrocław',1945,25000,'public','capital_or_large','https://pwr.edu.pl/en'),
('Rzeszów University of Technology','prz-rzeszow','PL','Rzeszów',1952,16000,'public','medium',NULL),
('Cardinal Stefan Wyszyński University Warsaw','uksw','PL','Warsaw',1999,16000,'public','capital_or_large','https://uksw.edu.pl/en'),
('Warsaw University of Life Sciences','sggw','PL','Warsaw',1816,16000,'public','capital_or_large','https://www.sggw.pl/en'),
('Medical University of Warsaw','wum','PL','Warsaw',1809,10000,'public','capital_or_large','https://www.wum.edu.pl/en'),
('Medical University of Łódź','umed-lodz','PL','Łódź',2002,10000,'public','capital_or_large','https://umed.lodz.pl/english'),
('Pomeranian Medical University Szczecin','pum-szczecin','PL','Szczecin',1948,7000,'public','medium','https://pums.edu.pl/en/'),
('Kozminski University','kozminski','PL','Warsaw',1993,9000,'private','capital_or_large','https://kozminski.edu.pl/en'),
('SWPS University of Social Sciences and Humanities','swps','PL','Warsaw',1996,15000,'private','capital_or_large','https://english.swps.pl/'),
('Lazarski University','lazarski','PL','Warsaw',1993,5000,'private','capital_or_large','https://www.lazarski.pl/en/'),
('Vistula University','vistula','PL','Warsaw',1996,8000,'private','capital_or_large','https://vistula.edu.pl/en'),
('WSB Merito University Warsaw','wsb-merito','PL','Warsaw',1994,20000,'private','capital_or_large','https://merito.pl/en'),
('Poznań University of Economics and Business','ue-poznan','PL','Poznań',1926,12000,'public','capital_or_large','https://ue.poznan.pl/en/'),
('SGH Warsaw School of Economics','sgh','PL','Warsaw',1906,13000,'public','capital_or_large','https://www.sgh.waw.pl/en/'),
('Cracow University of Economics','uek-krakow','PL','Kraków',1925,18000,'public','capital_or_large','https://uek.krakow.pl/en/'),
('University of Gdańsk','ug-gdansk','PL','Gdańsk',1970,23000,'public','capital_or_large','https://ug.edu.pl/en'),
('Opole University','uni-opole','PL','Opole',1994,15000,'public','small',NULL),
('University of Zielona Góra','uz-zgora','PL','Zielona Góra',2001,15000,'public','small',NULL),
-- ---------- ITALY (28 additional) ----------
('University of Padua','unipd','IT','Padova',1222,60000,'public','medium','https://www.unipd.it/en/'),
('University of Milan','unimi','IT','Milano',1924,60000,'public','capital_or_large','https://www.unimi.it/en'),
('University of Turin','unito','IT','Torino',1404,70000,'public','capital_or_large','https://en.unito.it/'),
('University of Naples Federico II','unina','IT','Napoli',1224,80000,'public','capital_or_large','https://www.international.unina.it/'),
('University of Florence','unifi','IT','Firenze',1321,51000,'public','medium','https://www.unifi.it/vp-8940-homepage.html'),
('University of Pisa','unipi','IT','Pisa',1343,50000,'public','small','https://www.unipi.it/index.php/english'),
('University of Pavia','unipv','IT','Pavia',1361,24000,'public','small','https://web-en.unipv.it/'),
('University of Trento','unitn','IT','Trento',1962,16000,'public','small','https://www.unitn.it/en'),
('University of Trieste','units','IT','Trieste',1924,23000,'public','medium','https://www.units.it/en'),
('Ca'' Foscari University of Venice','unive','IT','Venezia',1868,24000,'public','medium','https://www.unive.it/web/en/home'),
('Tor Vergata University of Rome','torvergata','IT','Roma',1982,40000,'public','capital_or_large','https://web.uniroma2.it/en'),
('Roma Tre University','roma3','IT','Roma',1992,35000,'public','capital_or_large','https://en.uniroma3.it/'),
('University of Bari Aldo Moro','uniba','IT','Bari',1924,55000,'public','medium','https://www.uniba.it/en/'),
('University of Catania','unict','IT','Catania',1434,38000,'public','medium','https://www.unict.it/en'),
('University of Palermo','unipa','IT','Palermo',1806,50000,'public','medium','https://www.unipa.it/portale/en/'),
('University of Genoa','unige','IT','Genova',1481,33000,'public','medium','https://www.unige.it/en/'),
('University of Verona','univr','IT','Verona',1982,25000,'public','small','https://www.verona.it/EN/Pagina/Home'),
('University of Parma','unipr','IT','Parma',1065,27000,'public','small','https://www.unipr.it/en'),
('University of Modena and Reggio Emilia','unimore','IT','Modena',1175,26000,'public','small','https://www.unimore.it/en'),
('University of Perugia','unipg','IT','Perugia',1308,31000,'public','small','https://www.unipg.it/en'),
('University of Calabria','unical','IT','Arcavacata di Rende',1972,30000,'public','small','https://www.unical.it/international'),
('University of Salerno','unisa-it','IT','Fisciano',1968,34000,'public','small','https://www.unisa.it/en'),
('University of Messina','unime','IT','Messina',1548,27000,'public','small','https://www.unime.it/en'),
('Gran Sasso Science Institute','gssi','IT','L''Aquila',2012,400,'public','small','https://www.gssi.it/'),
('University of Udine','uniud','IT','Udine',1978,15000,'public','small','https://www.uniud.it/en'),
('Politecnico di Torino','polito','IT','Torino',1859,35000,'public','capital_or_large','https://www.polito.it/english/'),
('Bocconi University','bocconi','IT','Milano',1902,15000,'private','capital_or_large','https://www.unibocconi.eu/'),
('LUISS Guido Carli','luiss','IT','Roma',1970,10000,'private','capital_or_large','https://www.luiss.it/en'),
('Vita-Salute San Raffaele University','unisr','IT','Milano',1996,4000,'private','capital_or_large','https://www.unisr.it/en'),
-- ---------- FRANCE (28 additional) ----------
('Université Paris Cité','paris-cite','FR','Paris',2019,63000,'public','capital_or_large','https://u-paris.fr/en/'),
('Aix-Marseille Université','amse-amu','FR','Marseille',1409,80000,'public','capital_or_large','https://www.univ-amu.fr/en'),
('Université Claude Bernard Lyon 1','ucbl-lyon','FR','Lyon',1971,46000,'public','capital_or_large','https://www.univ-lyon1.fr/en'),
('Université Jean Moulin Lyon 3','lyon3','FR','Lyon',1973,30000,'public','capital_or_large','https://www.univ-lyon3.fr/-anglais-.html'),
('Université Toulouse III Paul Sabatier','toulouse3','FR','Toulouse',1229,42000,'public','capital_or_large','https://www.univ-tlse3.fr/en'),
('Université de Montpellier','umontpellier','FR','Montpellier',1289,50000,'public','medium','https://www.umontpellier.fr/en/'),
('Université Côte d''Azur','uca-nice','FR','Nice',2015,30000,'public','capital_or_large','https://univ-cotedazur.eu/'),
('Université de Bordeaux','u-bordeaux','FR','Bordeaux',1441,56000,'public','capital_or_large','https://www.u-bordeaux.com/'),
('Université de Strasbourg','unistra','FR','Strasbourg',1538,52000,'public','capital_or_large','https://www.unistra.fr/index.php?id=home-en'),
('Université de Lille','univ-lille','FR','Lille',1559,74000,'public','capital_or_large','https://www.univ-lille.fr/en/'),
('Université de Rennes','univ-rennes','FR','Rennes',1461,30000,'public','small','https://www.univ-rennes.fr/en'),
('Université Grenoble Alpes','uga-grenoble','FR','Grenoble',1339,60000,'public','medium','https://www.univ-grenoble-alpes.fr/english/'),
('Nantes Université','univ-nantes','FR','Nantes',1460,43000,'public','capital_or_large','https://www.univ-nantes.fr/english-version'),
('Université Clermont Auvergne','uca-clermont','FR','Clermont-Ferrand',2017,35000,'public','medium','https://www.uca.fr/en'),
('Université de Tours','univ-tours','FR','Tours',1969,29000,'public','small','https://www.univ-tours.fr/international'),
('Université de Poitiers','univ-poitiers','FR','Poitiers',1431,27000,'public','small','https://www.univ-poitiers.fr/en/'),
('Université de Bourgogne','u-bourgogne','FR','Dijon',1722,30000,'public','small','https://www.u-bourgogne.fr/en'),
('Université de Picardie Jules Verne','upjv','FR','Amiens',1969,25000,'public','small','https://www.u-picardie.fr/?lang=en'),
('Université de Reims Champagne-Ardenne','univ-reims','FR','Reims',1548,25000,'public','small','https://www.univ-reims.fr/international'),
('Université Le Havre Normandie','univ-lehavre','FR','Le Havre',1984,10000,'public','capital_or_large',NULL),
('Université de Caen Normandie','unicaen','FR','Caen',1432,28000,'public','small','https://www.unicaen.fr/international/'),
('Université d''Orléans','univ-orleans','FR','Orléans',1306,20000,'public','small','https://www.univ-orleans.fr/en'),
('Université de Lorraine','univ-lorraine','FR','Nancy',1572,60000,'public','capital_or_large','https://www.univ-lorraine.fr/en'),
('Université d''Angers','univ-angers','FR','Angers',1337,25000,'public','small','https://www.univ-angers.fr/en/international.html'),
('École Polytechnique','polytechnique','FR','Palaiseau',1794,5000,'private','capital_or_large','https://www.polytechnique.edu/en'),
('Sciences Po','sciencespo','FR','Paris',1872,14000,'private','capital_or_large','https://www.sciencespo.fr/en/'),
('HEC Paris','hec-paris','FR','Paris',1881,4500,'private','capital_or_large','https://www.hec.edu/'),
('ESSEC Business School','essec','FR','Cergy',1907,6000,'private','capital_or_large','https://www.essec.edu/en/'),
-- ---------- SPAIN (26 additional) ----------
('Complutense University of Madrid','ucm','ES','Madrid',1293,75000,'public','capital_or_large','https://www.ucm.es/english'),
('Autonomous University of Barcelona','uab','ES','Barcelona',1968,40000,'public','capital_or_large','https://www.uab.cat/web/universitat-autonoma-de-barcelona-1345667984679.html'),
('Pompeu Fabra University','upf','ES','Barcelona',1990,15000,'public','capital_or_large','https://www.upf.edu/en/'),
('University of Valencia','uv-es','ES','Valencia',1499,45000,'public','capital_or_large','https://www.uv.es/uvweb/universidad/en/universitat-de-valencia-1285849687583.html'),
('University of Granada','ugr','ES','Granada',1531,47000,'public','small','https://www.ugr.es/en'),
('University of Seville','us-es','ES','Sevilla',1505,57000,'public','capital_or_large','https://www.us.es/eng/index.html'),
('University of Zaragoza','unizar','ES','Zaragoza',1542,30000,'public','medium','https://www.unizar.es/en'),
('University of Salamanca','usal','ES','Salamanca',1218,25000,'public','small','https://www.usal.es/en'),
('University of Valladolid','uva-es','ES','Valladolid',1241,21000,'public','small','https://www.uva.es/export/sites/uva/en/'),
('University of Santiago de Compostela','usc-galicia','ES','Santiago de Compostela',1495,30000,'public','small','https://www.usc.gal/en/index.html'),
('University of the Basque Country','ehu','ES','Leioa',1980,38000,'public','medium','https://www.ehu.eus/en/web/en/home'),
('University of Murcia','um-es','ES','Murcia',1914,30000,'public','medium','https://www.um.es/en/'),
('University of Málaga','uma-malaga','ES','Málaga',1972,35000,'public','medium','https://www.uma.es/'),
('Universidad Politécnica de Madrid','upm','ES','Madrid',1971,35000,'public','capital_or_large','https://www.upm.es/international'),
('Polytechnic University of Catalonia','upc','ES','Barcelona',1971,30000,'public','capital_or_large','https://www.upc.edu/en'),
('Carlos III University of Madrid','uc3m','ES','Madrid',1989,20000,'public','capital_or_large','https://www.uc3m.es/Home'),
('University of Alicante','ua-es','ES','Alicante',1979,27000,'public','medium','https://www.ua.es/en/'),
('University of Castilla-La Mancha','uclm','ES','Ciudad Real',1982,28000,'public','small','https://www.uclm.es/english'),
('University of Extremadura','unex','ES','Badajoz',1973,22000,'public','small','https://www.unex.es/conoce-la-uex/investigacion/grupos/grupos-lacomopt/english'),
('University of Córdoba','uco','ES','Córdoba',1972,21000,'public','small','https://www.uco.es/ucc/en/'),
('University of Navarra','unav','ES','Pamplona',1952,13000,'private','small','https://www.unav.edu.en/'),
('Ramon Llull University','url','ES','Barcelona',1990,15000,'private','capital_or_large','https://www.url.edu/en'),
('University of Deusto','deusto','ES','Bilbao',1886,11000,'private','capital_or_large','https://www.deusto.csic.es/?lang=en'),
('Comillas Pontifical University','comillas','ES','Madrid',1890,10000,'private','capital_or_large','https://www.comillas.edu/en/'),
('IE University','ie-university','ES','Segovia',1973,7000,'private','small','https://www.ie.edu/university/'),
('University of Oviedo','uniovi','ES','Oviedo',1608,22000,'public','small','https://www.uniovi.es/en'),
-- ---------- UNITED KINGDOM (27 additional) ----------
('University College London','ucl','GB','London',1826,44000,'public','capital_or_large','https://www.ucl.ac.uk/'),
('University of Edinburgh','edinburgh','GB','Edinburgh',1583,41000,'public','capital_or_large','https://www.ed.ac.uk/'),
('University of Manchester','manchester','GB','Manchester',1824,40000,'public','capital_or_large','https://www.manchester.ac.uk/'),
('King''s College London','kcl','GB','London',1829,33000,'public','capital_or_large','https://www.kcl.ac.uk/'),
('London School of Economics','lse','GB','London',1895,11000,'public','capital_or_large','https://www.lse.ac.uk/'),
('University of Bristol','bristol','GB','Bristol',1876,25000,'public','capital_or_large','https://www.bristol.ac.uk/'),
('University of Warwick','warwick','GB','Coventry',1965,24000,'public','medium','https://warwick.ac.uk/'),
('University of Glasgow','glasgow','GB','Glasgow',1451,29000,'public','capital_or_large','https://www.gla.ac.uk/'),
('University of Birmingham','birmingham','GB','Birmingham',1900,35000,'public','capital_or_large','https://www.birmingham.ac.uk/'),
('University of Leeds','leeds','GB','Leeds',1904,38000,'public','capital_or_large','https://www.leeds.ac.uk/'),
('University of Sheffield','sheffield','GB','Sheffield',1905,29000,'public','capital_or_large','https://www.sheffield.ac.uk/'),
('University of Nottingham','nottingham','GB','Nottingham',1881,34000,'public','medium','https://www.nottingham.ac.uk/'),
('University of Southampton','southampton','GB','Southampton',1952,25000,'public','medium','https://www.southampton.ac.uk/'),
('University of York','york-uk','GB','York',1963,19000,'public','small','https://www.york.ac.uk/'),
('Durham University','durham','GB','Durham',1832,22000,'public','small','https://www.durham.ac.uk/'),
('University of St Andrews','st-andrews','GB','St Andrews',1413,10000,'public','small','https://www.st-andrews.ac.uk/'),
('University of Liverpool','liverpool','GB','Liverpool',1881,27000,'public','capital_or_large','https://www.liverpool.ac.uk/'),
('Newcastle University','newcastle-uk','GB','Newcastle upon Tyne',1834,28000,'public','medium','https://www.ncl.ac.uk/'),
('Cardiff University','cardiff','GB','Cardiff',1883,30000,'public','capital_or_large','https://www.cardiff.ac.uk/'),
('University of Exeter','exeter','GB','Exeter',1955,29000,'public','medium','https://www.exeter.ac.uk/'),
("Queen''s University Belfast",'qub','GB','Belfast',1845,24000,'public','capital_or_large','https://www.qub.ac.uk/'),
('University of Aberdeen','aberdeen','GB','Aberdeen',1495,14000,'public','small','https://www.abdn.ac.uk/'),
('University of Bath','bath','GB','Bath',1966,20000,'public','small','https://www.bath.ac.uk/'),
('Lancaster University','lancaster','GB','Lancaster',1964,16000,'public','small','https://www.lancaster.ac.uk/'),
('University of Sussex','sussex','GB','Brighton',1961,18000,'public','medium','https://www.sussex.ac.uk/'),
('University of Surrey','surrey','GB','Guildford',1966,16000,'public','small','https://www.surrey.ac.uk/'),
('Loughborough University','loughborough','GB','Loughborough',1966,19000,'public','small','https://www.lboro.ac.uk/')
) as d(name,slug,cc,city,yr,students,own,csz,site)
where not exists (select 1 from universities u where u.name = d.name);
